In [1]:
import numpy as np

In [2]:
a = np.zeros([1, 10])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
b = np.ones([1, 10])
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
c = np.full([1, 10], 5)
c

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [13]:
d = np.arange(10, 51)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [14]:
e = np.arange(10, 51, 2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [21]:
f = np.arange(0, 9)
f.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.random.randint(0, 1)

0